##################### Lab Grafana behind reverse proxy #####################

[server]
protocol = http
http_port = 3000
domain = localhost
root_url = https://localhost/
serve_from_sub_path = false

[security]
admin_user = admin
admin_password = admin
cookie_secure = true

[metrics]
enabled = true

[users]
allow_sign_up = false
