apiVersion: 1

contactPoints:
  - orgId: 1
    name: ops-email
    receivers:
      - uid: ops-email-uid
        type: email
        settings:
          addresses: oncall@shopfront.lab
          singleEmail: false

policies:
  - orgId: 1
    receiver: ops-email
    group_by:
      - grafana_folder
      - alertname
    group_wait: 30s
    group_interval: 5m
    repeat_interval: 4h
